# Generated by Django 5.2.4 on 2025-07-28 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_bal', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Expense_track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('exp_type', models.CharField(choices=[('DR', 'Dr'), ('CR', 'Cr')], max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_bal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Expense.currentbalance')),
            ],
        ),
    ]
