# Generated by Django 5.2.4 on 2025-07-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_track',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
